### ISSUE TITLE
HTTP Server 'Bad Gateway' : https://otto.takari.io/content/sites/m2e.extras/m2eclipse-buildhelper/0.15.0/N/0.15.0.201405280027/content.xml

### ISSUE THREAD

**Issue by vorburger** [vorburger/opendaylight-eclipse-setup#5]
https://otto.takari.io is (just currently or permanently?) giving a HTTP 502 Bad Gateway (nginx/1.10.1) :

```
Fetching compositeContent.xml from http://m2e-code-quality.github.io/m2e-code-quality/site/
ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 HTTP Server 'Bad Gateway' : https://otto.takari.io/content/sites/m2e.extras/m2eclipse-buildhelper/0.15.0/N/0.15.0.201405280027/content.xml
ERROR: org.eclipse.ecf.identity code=0 HttpComponents connection error response code 502.
  at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:293)
  at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by vorburger** [comment]
seems to also be available on https://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-buildhelper/0.15.0/N/0.15.0.201405280027/ so let's better use that instead...

**Comment by vorburger** [comment]
BTW: Sources for this thing, if ever needed, on https://github.com/tesla/m2eclipse-buildhelper.

**Comment by vorburger** [comment]
FTR: Still not working as of right now, few minutes after commit... cached somewhere - where??

It will probably work in ... a few / 24 hours?
